# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1373ea672039c01c936cdcf7add4f501fb53ffa89d829a34b9e391f0115cff5b794f2ad80e12df6f065c938058c5fe425d4428fe70eaef04c31d45d306144fa

test:
  secret_key_base: 4567fad993e3279c9d50e181596105792ad876965a0dd4cc66fc0156142ce50f609736eacc50a89a84cb0d64bbad5ee7d64a90b52442be9f4a7296944e0d7c73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
